### ISSUE TITLE
Example ReserveZ bugs

### ISSUE THREAD

**Issue by HypnosNova** [austinEng/webgpu-samples#142]
![image](https://user-images.githubusercontent.com/7953802/132937562-6510f9de-81a5-47a7-83e6-5aa34a6d3b6c.png)
This error occurred in latest chrome canary

**Comment by shrekshao** [comment]
Not fully fixed, but for the reversed-Z sample, changing 
```diff
- layout: depthTextureBindGroupLayout,~~
+ layout: textureQuadPassPipline.getBindGroupLayout(0),
```
https://github.com/austinEng/webgpu-samples/blob/main/src/pages/samples/reversedZ.ts#L426

would make the mode == `depth-texture` path work.

but that `getBindGroupLayout(0)` corresponds to 
```
[[group(0), binding(0)]] var depthTexture: texture_depth_2d;
```
which I don't know the difference than
```typescript
const depthTextureBindGroupLayout = device.createBindGroupLayout({
    entries: [
      {
        binding: 0,
        visibility: GPUShaderStage.FRAGMENT,
        texture: {
          sampleType: 'depth',
        },
      },
    ],
  });
```

enga@ can you give some instructions here?

Now shaowMapping, ReversedZ, and deferredRendering all fails due to similiar bind group issues. Might be some systematic misunderstanding by me

**Comment by kainino0x** [comment]
I think this is because of https://github.com/gpuweb/gpuweb/pull/2057
If your bind group uses an explicitly-created bind group layout, then the pipeline must also be created from that bind group layout (rather than implicitly).

**Comment by shrekshao** [comment]
Ah! Thanks for the pointer. New knowledge aquired

**Comment by shrekshao** [comment]
Fixed. Thanks for the report!
