### ISSUE TITLE
Samples broken in latest Chrome, Edge Canary

### ISSUE THREAD

**Issue by drdavidbrown** [austinEng/webgpu-samples#183]
All samples appear to be broken with latest Chrome and Edge Canary builds, failing with "GPU Connection Lost".
Chrome Canary Version 104.0.5066.0 (Official Build) canary (64-bit)
Edge Canary version 103.0.1259.0 (Official build) canary (64-bit).
Windows 10

**Comment by austinEng** [comment]
Hi, this issue is crbug.com/1322823.
A fix was landed in https://chromium-review.googlesource.com/c/chromium/src/+/3648575

You can track when it is available in Canary here: https://chromiumdash.appspot.com/commit/2ab3924df9894cfba339ce1765eab3d3da22994f

I'll close this since it's not an issue with the samples themselves.
